### ISSUE TITLE
你们的readme中提到的sdk版本是1.1.6，但是没有啊，pod install 老报错

### ISSUE THREAD

**Issue by Bogon** [V5KF/V5KFClientSDK-iOS#1]
你们的readme中提到的sdk版本是1.1.6，但是没有啊，pod install 老报错。求解，1.1.5版本还能用吗？在线等！

<img width="586" alt="2016-06-27 10 27 40" src="https://cloud.githubusercontent.com/assets/6748372/16383182/9e70b858-3cb6-11e6-940e-7ce7b3006b4e.png">

**Comment by V5KF** [comment]
pod 1.1.6今天刚更新，尚未验证，有问题的话可以先用1.1.5，可以用的，明天解决这个问题到时候可以更新(1.1.6修复开场白设置问题)

**Comment by Bogon** [comment]
好的，谢谢。

**Comment by Bogon** [comment]
<img width="589" alt="2016-07-17 2 32 20" src="https://cloud.githubusercontent.com/assets/6748372/16899135/67051902-4c2b-11e6-9450-2b29df75d36e.png">

不太明白你们的这个sdk，在pod上已经搜索不到了？在线等

**Comment by Chyrain** [comment]
真的吗？回头我批评pod去 ，一定让他给我弄回来

**Comment by V5KF** [comment]
<img width="506" alt="6df9f396-b057-4064-88ae-abaf24eb456b" src="https://cloud.githubusercontent.com/assets/19440430/16904701/334a4ce8-4ccd-11e6-9377-5500bfebf9d7.png">
有的哦，你检查一下是不是pod有问题，这边是可以search到的
