### ISSUE TITLE
Dependency "V5KFClientSDK-iOS" has no shared framework schemes

### ISSUE THREAD

**Issue by tangkunyin** [V5KF/V5KFClientSDK-iOS#2]
`Dependency "V5KFClientSDK-iOS" has no shared framework schemes`
用`carthage`更新时，遇到这个问题，麻烦把`sheme`那里勾选为`shared`。谢谢

**Comment by tangkunyin** [comment]
@V5KF 如果能提供一份动态库再好不过了，`libV5Client.a`文件就40多兆，好难受！！！
具体打包方式可参考：https://onevcat.com/2016/01/create-framework/

**Comment by V5KF** [comment]
小五了解了，上班后会努力提供出来的。

**Comment by tangkunyin** [comment]
@V5KF 谢谢。刚看了更新提交日志，您是把`ClientDemo`的`scheme`改成了`shared`，不过这对开发者没什么影响啊。我是说那SDK包，打SDK包的工程里改一下。能编译成`framework`动态库最好不过。

**Comment by V5KF** [comment]
我也觉得纳闷啊，非开发环境不太方便，所以试改了下demo，感觉是没什么作用的。要重新打包静态库才行，上班处理

**Comment by V5KF** [comment]
麻烦稍等

**Comment by tangkunyin** [comment]
@V5KF 非常感谢，弄好了麻烦通知下大家伙 :)

**Comment by tangkunyin** [comment]
@V5KF @Chyrain 您好，看到更新了，果断尝试，但还是用不了！您可以通过依赖管理工具`Carthage`试试看，而不是把`framework`拖进工程里！

<img width="1436" alt="v5kf" src="https://cloud.githubusercontent.com/assets/4197468/26383137/c8182b94-4063-11e7-83ea-5ba4c787495d.png">

**Comment by tangkunyin** [comment]
@V5KF @Chyrain 另外，V5KF的服务器貌似不太稳定，北京这边有个现象就是WIFI连不上，包括官方提供的客服APP都登录不了，但换成3G、4G又没问题！不是我一个人出现的情况，有可能是我的幻觉......

**Comment by V5KF** [comment]
@tangkunyin  看是哪家运营商的网络，貌似北京那边有家DNS有问题。另外在https://github.com/V5KF/V5ClientFramework-iOS 已经测试成功了的，刚转移到V5KFClientSDK-iOS还在测试中，这两天上传github实在太卡，提交太慢浪费了点时间

**Comment by V5KF** [comment]
@tangkunyin 具体访问不了的问题可以到官网咨询下客服，看看什么情况

**Comment by V5KF** [comment]
刚刚试了下是可以的了，并不是简单把framework拖进工程里，而是
 https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file 不开放源码的方式就是打包V5Client.framework.zip了吧
![image](https://cloud.githubusercontent.com/assets/19440430/26383941/77346e90-4068-11e7-8e45-0e2438f615a1.png)

**Comment by tangkunyin** [comment]
@V5KF 好的，多谢你们！
