### ISSUE TITLE
app提审时，遇到了包的问题

### ISSUE THREAD

**Issue by tangkunyin** [V5KF/V5KFClientSDK-iOS#3]
如下
<img width="815" alt="v5" src="https://user-images.githubusercontent.com/4197468/29854181-eb64a338-8d76-11e7-968e-8d54928134ea.png">

个人觉得现在iOS8以下基本上都被抛弃了，如果咱的库还在兼容iOS8以下，势必造成动态库混合使用时，出现最低版本约束的问题

**Comment by V5KF** [comment]
了解，确实有MinimumOSVersion问题，马上更正动态库的最低版本，您可以先试试修改framework下的Info.plist文件MinimumOSVersion改为8.0

**Comment by tangkunyin** [comment]
<img width="1084" alt="error" src="https://user-images.githubusercontent.com/4197468/30677729-1b7f5512-9e53-11e7-8223-6c721b9a919f.png">

**Comment by tangkunyin** [comment]
@V5KF @Chyrain 您好，这几天Xcode9正式版和Swift4正式版都出来了，用了1.3.4的库，提交不上去，麻烦看看，谢谢！！

**Comment by Chyrain** [comment]
@tangkunyin 抱歉，新版本适配不够及时，如果可以尽量先不用新版Xcode，我们这边会尽快更新

**Comment by Chyrain** [comment]
@tangkunyin 可以试下1.3.5，看看提审是否还有问题

**Comment by tangkunyin** [comment]
@Chyrain 现在可以了，谢谢你们的迅速支持，感谢，加油！
